FROM pihole/pihole:latest
RUN apt update && apt install -y unbound wget net-tools

COPY lighttpd-external.conf /etc/lighttpd/external.conf
COPY unbound-pihole.conf /etc/unbound/unbound.conf.d/pi-hole.conf
COPY start_unbound_and_s6_init.sh start_unbound_and_s6_init.sh

RUN wget https://www.internic.net/domain/named.root -O /var/lib/unbound/root.hints

RUN chmod +x start_unbound_and_s6_init.sh
ENTRYPOINT ./start_unbound_and_s6_init.sh
